import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import { SidebarProvider } from '@/contexts/SidebarContextProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: `GameDevUtopia - A student-run Game Developers' Club`,
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SidebarProvider>

          <div className='w-full flex'>
            <div className='sm:w-[4%] z-50 sm:inline'>
              <Navbar />
            </div>
            <div className='sm:w-[90%] w-full'>
              {children}
            </div>
          </div>
          <Footer />
        </SidebarProvider>
      </body>
    </html>
  )
}
