import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import { SidebarProvider } from '@/contexts/SidebarContextProvider'
import Script from 'next/script';
import GoogleTagManager from '@/components/Analytics/GoogleTagManager';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: `GameDevUtopia - A student-run Game Developers' Club`,
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <Script id="gtm" strategy="afterInteractive">
          {`(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
          new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
          j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
          'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
          })(window,document,'script','dataLayer','GTM-G-GGQ8NSHNDR');`} 
        </Script>
      </head>
      <body className={"bg-slate-900"}>

        <SidebarProvider>
          <div className='w-full'>
            <div className='w-full bg-slate-900 flex'>
              <GoogleTagManager />
              <Navbar />
              <div className='w-screen  md:w-[96.5vw] relative top-[5.5rem] sm:left-[3.5vw]'>
                {children}
              </div>
            </div>
            <Footer />
          </div>
        </SidebarProvider>
      </body>
    </html>
  )
}
