import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import { SidebarProvider } from '@/contexts/SidebarContextProvider'
import Script from 'next/script';
import GoogleTagManager from '@/components/Analytics/GoogleTagManager';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: `GameDevUtopia - A student-run Game Developers' Club`,
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Google Tag Manager Script */}
        <script async src="https://www.googletagmanager.com/gtag/js?id=G-GGQ8NSHNDR" strategy="afterInteractive"></script>
        <script
          id="google-analytics"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `
              window.dataLayer = window.dataLayer || [];
              function gtag(){window.dataLayer.push(arguments);}
              gtag('js', new Date());
              gtag('config', 'G-GGQ8NSHNDR');
            `,
          }}
        />
      </head>
      <body className={"bg-slate-900"}>
        <SidebarProvider>
          <div className='w-full'>
            <div className='w-full bg-slate-900 flex'>
              <GoogleTagManager />
              <Navbar />
              <div className='w-screen  md:w-[96.5vw] relative top-[5.5rem] sm:left-[3.5vw]'>
                {children}
              </div>
            </div>
            <Footer />
          </div>
        </SidebarProvider>
      </body>
    </html>
  )
}
